name: Terraform_CI   ##workflow name

on:   ###event trigger
 push:   ####event method
    branches:
     - main   ####source code

jobs:
   terraform_CI:   ###########Jobid
      name: terraform CI(download , checkout & init)    #########logical job name
      runs-on: ubuntu-latest  #########runner for this job
      steps:
        - name: Install terraform
          uses: hashicorp/setup-terraform@v3
        - name: check out the code
          uses: actions/checkout@v4
        - name: terraform init
          working-directory: envs/dev
          run: terraform init


       
  
    
  
